/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as KpiReportsRouteImport } from './routes/kpi-reports'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as UserAccessRouteImport } from './routes/user-access'
import { Route as WorklogsRouteImport } from './routes/worklogs'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as MeAnnouncementsRouteImport } from './routes/me.announcements'
import { Route as MeAttendanceRouteImport } from './routes/me.attendance'
import { Route as MeBoardRouteImport } from './routes/me.board'
import { Route as MeChatRouteImport } from './routes/me.chat'
import { Route as MeKpiRouteImport } from './routes/me.kpi'
import { Route as MeLeaveRouteImport } from './routes/me.leave'
import { Route as MeMeetingsRouteImport } from './routes/me.meetings'
import { Route as MePayslipsRouteImport } from './routes/me.payslips'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as MeWorklogsRouteImport } from './routes/me.worklogs'
import { Route as OnboardingTokenRouteImport } from './routes/onboarding.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiReportsRoute = KpiReportsRouteImport.update({
  id: '/kpi-reports',
  path: '/kpi-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAccessRoute = UserAccessRouteImport.update({
  id: '/user-access',
  path: '/user-access',
  getParentRoute: () => rootRouteImport,
} as any)
const WorklogsRoute = WorklogsRouteImport.update({
  id: '/worklogs',
  path: '/worklogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeAnnouncementsRoute = MeAnnouncementsRouteImport.update({
  id: '/me/announcements',
  path: '/me/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const MeAttendanceRoute = MeAttendanceRouteImport.update({
  id: '/me/attendance',
  path: '/me/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const MeBoardRoute = MeBoardRouteImport.update({
  id: '/me/board',
  path: '/me/board',
  getParentRoute: () => rootRouteImport,
} as any)
const MeChatRoute = MeChatRouteImport.update({
  id: '/me/chat',
  path: '/me/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MeKpiRoute = MeKpiRouteImport.update({
  id: '/me/kpi',
  path: '/me/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const MeLeaveRoute = MeLeaveRouteImport.update({
  id: '/me/leave',
  path: '/me/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const MeMeetingsRoute = MeMeetingsRouteImport.update({
  id: '/me/meetings',
  path: '/me/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MePayslipsRoute = MePayslipsRouteImport.update({
  id: '/me/payslips',
  path: '/me/payslips',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MeWorklogsRoute = MeWorklogsRouteImport.update({
  id: '/me/worklogs',
  path: '/me/worklogs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTokenRoute = OnboardingTokenRouteImport.update({
  id: '/onboarding/$token',
  path: '/onboarding/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/chat': typeof ChatRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/holidays': typeof HolidaysRoute
  '/kpi-reports': typeof KpiReportsRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/monitoring': typeof MonitoringRoute
  '/payroll': typeof PayrollRoute
  '/projects': typeof ProjectsRoute
  '/schedules': typeof SchedulesRoute
  '/user-access': typeof UserAccessRoute
  '/worklogs': typeof WorklogsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/me/announcements': typeof MeAnnouncementsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/board': typeof MeBoardRoute
  '/me/chat': typeof MeChatRoute
  '/me/kpi': typeof MeKpiRoute
  '/me/leave': typeof MeLeaveRoute
  '/me/meetings': typeof MeMeetingsRoute
  '/me/payslips': typeof MePayslipsRoute
  '/me/profile': typeof MeProfileRoute
  '/me/worklogs': typeof MeWorklogsRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/chat': typeof ChatRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/holidays': typeof HolidaysRoute
  '/kpi-reports': typeof KpiReportsRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/monitoring': typeof MonitoringRoute
  '/payroll': typeof PayrollRoute
  '/projects': typeof ProjectsRoute
  '/schedules': typeof SchedulesRoute
  '/user-access': typeof UserAccessRoute
  '/worklogs': typeof WorklogsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/me/announcements': typeof MeAnnouncementsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/board': typeof MeBoardRoute
  '/me/chat': typeof MeChatRoute
  '/me/kpi': typeof MeKpiRoute
  '/me/leave': typeof MeLeaveRoute
  '/me/meetings': typeof MeMeetingsRoute
  '/me/payslips': typeof MePayslipsRoute
  '/me/profile': typeof MeProfileRoute
  '/me/worklogs': typeof MeWorklogsRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/me': typeof MeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/chat': typeof ChatRoute
  '/departments': typeof DepartmentsRoute
  '/employees': typeof EmployeesRoute
  '/holidays': typeof HolidaysRoute
  '/kpi-reports': typeof KpiReportsRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/monitoring': typeof MonitoringRoute
  '/payroll': typeof PayrollRoute
  '/projects': typeof ProjectsRoute
  '/schedules': typeof SchedulesRoute
  '/user-access': typeof UserAccessRoute
  '/worklogs': typeof WorklogsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/me/announcements': typeof MeAnnouncementsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/board': typeof MeBoardRoute
  '/me/chat': typeof MeChatRoute
  '/me/kpi': typeof MeKpiRoute
  '/me/leave': typeof MeLeaveRoute
  '/me/meetings': typeof MeMeetingsRoute
  '/me/payslips': typeof MePayslipsRoute
  '/me/profile': typeof MeProfileRoute
  '/me/worklogs': typeof MeWorklogsRoute
  '/onboarding/$token': typeof OnboardingTokenRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/chat'
    | '/departments'
    | '/employees'
    | '/holidays'
    | '/kpi-reports'
    | '/leave'
    | '/login'
    | '/meetings'
    | '/monitoring'
    | '/payroll'
    | '/projects'
    | '/schedules'
    | '/user-access'
    | '/worklogs'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/me/announcements'
    | '/me/attendance'
    | '/me/board'
    | '/me/chat'
    | '/me/kpi'
    | '/me/leave'
    | '/me/meetings'
    | '/me/payslips'
    | '/me/profile'
    | '/me/worklogs'
    | '/onboarding/$token'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/chat'
    | '/departments'
    | '/employees'
    | '/holidays'
    | '/kpi-reports'
    | '/leave'
    | '/login'
    | '/meetings'
    | '/monitoring'
    | '/payroll'
    | '/projects'
    | '/schedules'
    | '/user-access'
    | '/worklogs'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/me/announcements'
    | '/me/attendance'
    | '/me/board'
    | '/me/chat'
    | '/me/kpi'
    | '/me/leave'
    | '/me/meetings'
    | '/me/payslips'
    | '/me/profile'
    | '/me/worklogs'
    | '/onboarding/$token'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/attendance'
    | '/chat'
    | '/departments'
    | '/employees'
    | '/holidays'
    | '/kpi-reports'
    | '/leave'
    | '/login'
    | '/meetings'
    | '/monitoring'
    | '/payroll'
    | '/projects'
    | '/schedules'
    | '/user-access'
    | '/worklogs'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/me/announcements'
    | '/me/attendance'
    | '/me/board'
    | '/me/chat'
    | '/me/kpi'
    | '/me/leave'
    | '/me/meetings'
    | '/me/payslips'
    | '/me/profile'
    | '/me/worklogs'
    | '/onboarding/$token'
    | '/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  ChatRoute: typeof ChatRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EmployeesRoute: typeof EmployeesRoute
  HolidaysRoute: typeof HolidaysRoute
  KpiReportsRoute: typeof KpiReportsRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MonitoringRoute: typeof MonitoringRoute
  PayrollRoute: typeof PayrollRoute
  ProjectsRoute: typeof ProjectsRoute
  SchedulesRoute: typeof SchedulesRoute
  UserAccessRoute: typeof UserAccessRoute
  WorklogsRoute: typeof WorklogsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  MeAnnouncementsRoute: typeof MeAnnouncementsRoute
  MeAttendanceRoute: typeof MeAttendanceRoute
  MeBoardRoute: typeof MeBoardRoute
  MeChatRoute: typeof MeChatRoute
  MeKpiRoute: typeof MeKpiRoute
  MeLeaveRoute: typeof MeLeaveRoute
  MeMeetingsRoute: typeof MeMeetingsRoute
  MePayslipsRoute: typeof MePayslipsRoute
  MeProfileRoute: typeof MeProfileRoute
  MeWorklogsRoute: typeof MeWorklogsRoute
  OnboardingTokenRoute: typeof OnboardingTokenRoute
  MeIndexRoute: typeof MeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi-reports': {
      id: '/kpi-reports'
      path: '/kpi-reports'
      fullPath: '/kpi-reports'
      preLoaderRoute: typeof KpiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-access': {
      id: '/user-access'
      path: '/user-access'
      fullPath: '/user-access'
      preLoaderRoute: typeof UserAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worklogs': {
      id: '/worklogs'
      path: '/worklogs'
      fullPath: '/worklogs'
      preLoaderRoute: typeof WorklogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/announcements': {
      id: '/me/announcements'
      path: '/me/announcements'
      fullPath: '/me/announcements'
      preLoaderRoute: typeof MeAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/attendance': {
      id: '/me/attendance'
      path: '/me/attendance'
      fullPath: '/me/attendance'
      preLoaderRoute: typeof MeAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/board': {
      id: '/me/board'
      path: '/me/board'
      fullPath: '/me/board'
      preLoaderRoute: typeof MeBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/chat': {
      id: '/me/chat'
      path: '/me/chat'
      fullPath: '/me/chat'
      preLoaderRoute: typeof MeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/kpi': {
      id: '/me/kpi'
      path: '/me/kpi'
      fullPath: '/me/kpi'
      preLoaderRoute: typeof MeKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/leave': {
      id: '/me/leave'
      path: '/me/leave'
      fullPath: '/me/leave'
      preLoaderRoute: typeof MeLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/meetings': {
      id: '/me/meetings'
      path: '/me/meetings'
      fullPath: '/me/meetings'
      preLoaderRoute: typeof MeMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/payslips': {
      id: '/me/payslips'
      path: '/me/payslips'
      fullPath: '/me/payslips'
      preLoaderRoute: typeof MePayslipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/worklogs': {
      id: '/me/worklogs'
      path: '/me/worklogs'
      fullPath: '/me/worklogs'
      preLoaderRoute: typeof MeWorklogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$token': {
      id: '/onboarding/$token'
      path: '/onboarding/$token'
      fullPath: '/onboarding/$token'
      preLoaderRoute: typeof OnboardingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  ChatRoute: ChatRoute,
  DepartmentsRoute: DepartmentsRoute,
  EmployeesRoute: EmployeesRoute,
  HolidaysRoute: HolidaysRoute,
  KpiReportsRoute: KpiReportsRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MonitoringRoute: MonitoringRoute,
  PayrollRoute: PayrollRoute,
  ProjectsRoute: ProjectsRoute,
  SchedulesRoute: SchedulesRoute,
  UserAccessRoute: UserAccessRoute,
  WorklogsRoute: WorklogsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  MeAnnouncementsRoute: MeAnnouncementsRoute,
  MeAttendanceRoute: MeAttendanceRoute,
  MeBoardRoute: MeBoardRoute,
  MeChatRoute: MeChatRoute,
  MeKpiRoute: MeKpiRoute,
  MeLeaveRoute: MeLeaveRoute,
  MeMeetingsRoute: MeMeetingsRoute,
  MePayslipsRoute: MePayslipsRoute,
  MeProfileRoute: MeProfileRoute,
  MeWorklogsRoute: MeWorklogsRoute,
  OnboardingTokenRoute: OnboardingTokenRoute,
  MeIndexRoute: MeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
